// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: grader.proto

package proto

import (
	proto "autograder-server/pkg/model/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterGraderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Info  *proto.GraderInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *RegisterGraderRequest) Reset() {
	*x = RegisterGraderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGraderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGraderRequest) ProtoMessage() {}

func (x *RegisterGraderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGraderRequest.ProtoReflect.Descriptor instead.
func (*RegisterGraderRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGraderRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterGraderRequest) GetInfo() *proto.GraderInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type RegisterGraderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraderId uint64 `protobuf:"varint,1,opt,name=grader_id,json=graderId,proto3" json:"grader_id,omitempty"`
}

func (x *RegisterGraderResponse) Reset() {
	*x = RegisterGraderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGraderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGraderResponse) ProtoMessage() {}

func (x *RegisterGraderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGraderResponse.ProtoReflect.Descriptor instead.
func (*RegisterGraderResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterGraderResponse) GetGraderId() uint64 {
	if x != nil {
		return x.GraderId
	}
	return 0
}

type GraderHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	GraderId    uint64                 `protobuf:"varint,2,opt,name=grader_id,json=graderId,proto3" json:"grader_id,omitempty"`
	Concurrency uint64                 `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
}

func (x *GraderHeartbeatRequest) Reset() {
	*x = GraderHeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraderHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraderHeartbeatRequest) ProtoMessage() {}

func (x *GraderHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraderHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*GraderHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{2}
}

func (x *GraderHeartbeatRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GraderHeartbeatRequest) GetGraderId() uint64 {
	if x != nil {
		return x.GraderId
	}
	return 0
}

func (x *GraderHeartbeatRequest) GetConcurrency() uint64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type GraderHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*GradeRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GraderHeartbeatResponse) Reset() {
	*x = GraderHeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraderHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraderHeartbeatResponse) ProtoMessage() {}

func (x *GraderHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraderHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*GraderHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{3}
}

func (x *GraderHeartbeatResponse) GetRequests() []*GradeRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type GradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmissionId uint64                             `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Submission   *proto.Submission                  `protobuf:"bytes,2,opt,name=submission,proto3" json:"submission,omitempty"`
	Config       *proto.ProgrammingAssignmentConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	IsCancel     bool                               `protobuf:"varint,4,opt,name=is_cancel,json=isCancel,proto3" json:"is_cancel,omitempty"`
}

func (x *GradeRequest) Reset() {
	*x = GradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeRequest) ProtoMessage() {}

func (x *GradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeRequest.ProtoReflect.Descriptor instead.
func (*GradeRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{4}
}

func (x *GradeRequest) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *GradeRequest) GetSubmission() *proto.Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

func (x *GradeRequest) GetConfig() *proto.ProgrammingAssignmentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GradeRequest) GetIsCancel() bool {
	if x != nil {
		return x.IsCancel
	}
	return false
}

type GradeReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report         *proto.SubmissionReport      `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Brief          *proto.SubmissionBriefReport `protobuf:"bytes,2,opt,name=brief,proto3" json:"brief,omitempty"`
	DockerMetadata *DockerGraderMetadata        `protobuf:"bytes,3,opt,name=docker_metadata,json=dockerMetadata,proto3" json:"docker_metadata,omitempty"`
}

func (x *GradeReport) Reset() {
	*x = GradeReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeReport) ProtoMessage() {}

func (x *GradeReport) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeReport.ProtoReflect.Descriptor instead.
func (*GradeReport) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{5}
}

func (x *GradeReport) GetReport() *proto.SubmissionReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GradeReport) GetBrief() *proto.SubmissionBriefReport {
	if x != nil {
		return x.Brief
	}
	return nil
}

func (x *GradeReport) GetDockerMetadata() *DockerGraderMetadata {
	if x != nil {
		return x.DockerMetadata
	}
	return nil
}

type GradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmissionId uint64       `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Report       *GradeReport `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{6}
}

func (x *GradeResponse) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *GradeResponse) GetReport() *GradeReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type GradeCallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GradeCallbackResponse) Reset() {
	*x = GradeCallbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeCallbackResponse) ProtoMessage() {}

func (x *GradeCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeCallbackResponse.ProtoReflect.Descriptor instead.
func (*GradeCallbackResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{7}
}

type GetAllMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraderId uint64 `protobuf:"varint,1,opt,name=grader_id,json=graderId,proto3" json:"grader_id,omitempty"`
}

func (x *GetAllMetadataRequest) Reset() {
	*x = GetAllMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetadataRequest) ProtoMessage() {}

func (x *GetAllMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetAllMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllMetadataRequest) GetGraderId() uint64 {
	if x != nil {
		return x.GraderId
	}
	return 0
}

type GetAllMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys   [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *GetAllMetadataResponse) Reset() {
	*x = GetAllMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetadataResponse) ProtoMessage() {}

func (x *GetAllMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetAllMetadataResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllMetadataResponse) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetAllMetadataResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type PutMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraderId uint64 `protobuf:"varint,1,opt,name=grader_id,json=graderId,proto3" json:"grader_id,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutMetadataRequest) Reset() {
	*x = PutMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetadataRequest) ProtoMessage() {}

func (x *PutMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetadataRequest.ProtoReflect.Descriptor instead.
func (*PutMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{10}
}

func (x *PutMetadataRequest) GetGraderId() uint64 {
	if x != nil {
		return x.GraderId
	}
	return 0
}

func (x *PutMetadataRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutMetadataRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutMetadataResponse) Reset() {
	*x = PutMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetadataResponse) ProtoMessage() {}

func (x *PutMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetadataResponse.ProtoReflect.Descriptor instead.
func (*PutMetadataResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{11}
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GraderId uint64 `protobuf:"varint,1,opt,name=grader_id,json=graderId,proto3" json:"grader_id,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetadataRequest) GetGraderId() uint64 {
	if x != nil {
		return x.GraderId
	}
	return 0
}

func (x *GetMetadataRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetadataResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DockerGraderMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubmissionId uint64 `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	ContainerId  string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (x *DockerGraderMetadata) Reset() {
	*x = DockerGraderMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grader_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerGraderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerGraderMetadata) ProtoMessage() {}

func (x *DockerGraderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_grader_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerGraderMetadata.ProtoReflect.Descriptor instead.
func (*DockerGraderMetadata) Descriptor() ([]byte, []int) {
	return file_grader_proto_rawDescGZIP(), []int{14}
}

func (x *DockerGraderMetadata) GetSubmissionId() uint64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *DockerGraderMetadata) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_grader_proto protoreflect.FileDescriptor

var file_grader_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x15,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x16,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x16, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x44, 0x0a,
	0x17, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x0c, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x6d, 0x69, 0x6e, 0x67, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x22, 0xa6, 0x01, 0x0a, 0x0b, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x62, 0x72, 0x69,
	0x65, 0x66, 0x12, 0x3e, 0x0a, 0x0f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x44, 0x6f,
	0x63, 0x6b, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x0e, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x5a, 0x0a, 0x0d, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x17,
	0x0a, 0x15, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x44, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x15,
	0x0a, 0x13, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2b, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e, 0x0a, 0x14, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x32, 0xc1, 0x03, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x72, 0x48, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x0d, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x0f, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x17, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x0d, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x16, 0x2e, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x13, 0x2e,
	0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x61,
	0x75, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grader_proto_rawDescOnce sync.Once
	file_grader_proto_rawDescData = file_grader_proto_rawDesc
)

func file_grader_proto_rawDescGZIP() []byte {
	file_grader_proto_rawDescOnce.Do(func() {
		file_grader_proto_rawDescData = protoimpl.X.CompressGZIP(file_grader_proto_rawDescData)
	})
	return file_grader_proto_rawDescData
}

var file_grader_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_grader_proto_goTypes = []interface{}{
	(*RegisterGraderRequest)(nil),             // 0: RegisterGraderRequest
	(*RegisterGraderResponse)(nil),            // 1: RegisterGraderResponse
	(*GraderHeartbeatRequest)(nil),            // 2: GraderHeartbeatRequest
	(*GraderHeartbeatResponse)(nil),           // 3: GraderHeartbeatResponse
	(*GradeRequest)(nil),                      // 4: GradeRequest
	(*GradeReport)(nil),                       // 5: GradeReport
	(*GradeResponse)(nil),                     // 6: GradeResponse
	(*GradeCallbackResponse)(nil),             // 7: GradeCallbackResponse
	(*GetAllMetadataRequest)(nil),             // 8: GetAllMetadataRequest
	(*GetAllMetadataResponse)(nil),            // 9: GetAllMetadataResponse
	(*PutMetadataRequest)(nil),                // 10: PutMetadataRequest
	(*PutMetadataResponse)(nil),               // 11: PutMetadataResponse
	(*GetMetadataRequest)(nil),                // 12: GetMetadataRequest
	(*GetMetadataResponse)(nil),               // 13: GetMetadataResponse
	(*DockerGraderMetadata)(nil),              // 14: DockerGraderMetadata
	(*proto.GraderInfo)(nil),                  // 15: GraderInfo
	(*timestamppb.Timestamp)(nil),             // 16: google.protobuf.Timestamp
	(*proto.Submission)(nil),                  // 17: Submission
	(*proto.ProgrammingAssignmentConfig)(nil), // 18: ProgrammingAssignmentConfig
	(*proto.SubmissionReport)(nil),            // 19: SubmissionReport
	(*proto.SubmissionBriefReport)(nil),       // 20: SubmissionBriefReport
}
var file_grader_proto_depIdxs = []int32{
	15, // 0: RegisterGraderRequest.info:type_name -> GraderInfo
	16, // 1: GraderHeartbeatRequest.time:type_name -> google.protobuf.Timestamp
	4,  // 2: GraderHeartbeatResponse.requests:type_name -> GradeRequest
	17, // 3: GradeRequest.submission:type_name -> Submission
	18, // 4: GradeRequest.config:type_name -> ProgrammingAssignmentConfig
	19, // 5: GradeReport.report:type_name -> SubmissionReport
	20, // 6: GradeReport.brief:type_name -> SubmissionBriefReport
	14, // 7: GradeReport.docker_metadata:type_name -> DockerGraderMetadata
	5,  // 8: GradeResponse.report:type_name -> GradeReport
	0,  // 9: GraderHubService.RegisterGrader:input_type -> RegisterGraderRequest
	4,  // 10: GraderHubService.Grade:input_type -> GradeRequest
	2,  // 11: GraderHubService.GraderHeartbeat:input_type -> GraderHeartbeatRequest
	6,  // 12: GraderHubService.GradeCallback:input_type -> GradeResponse
	12, // 13: GraderHubService.GetMetadata:input_type -> GetMetadataRequest
	10, // 14: GraderHubService.PutMetadata:input_type -> PutMetadataRequest
	8,  // 15: GraderHubService.GetAllMetadata:input_type -> GetAllMetadataRequest
	1,  // 16: GraderHubService.RegisterGrader:output_type -> RegisterGraderResponse
	7,  // 17: GraderHubService.Grade:output_type -> GradeCallbackResponse
	3,  // 18: GraderHubService.GraderHeartbeat:output_type -> GraderHeartbeatResponse
	7,  // 19: GraderHubService.GradeCallback:output_type -> GradeCallbackResponse
	13, // 20: GraderHubService.GetMetadata:output_type -> GetMetadataResponse
	11, // 21: GraderHubService.PutMetadata:output_type -> PutMetadataResponse
	9,  // 22: GraderHubService.GetAllMetadata:output_type -> GetAllMetadataResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_grader_proto_init() }
func file_grader_proto_init() {
	if File_grader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterGraderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterGraderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraderHeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraderHeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeCallbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grader_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerGraderMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grader_proto_goTypes,
		DependencyIndexes: file_grader_proto_depIdxs,
		MessageInfos:      file_grader_proto_msgTypes,
	}.Build()
	File_grader_proto = out.File
	file_grader_proto_rawDesc = nil
	file_grader_proto_goTypes = nil
	file_grader_proto_depIdxs = nil
}
