name: Build
on: [push]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: |
            pkg/web/dist
          key: autograder-web-${{ github.sha }}
      - run: npm install -g @angular/cli
      - run: cd web && npm install
      - run: cd web && ng build --output-path ../pkg/web/dist

  build-server:
    runs-on: ubuntu-latest
    needs: build-web
    strategy:
      matrix:
        GOOS: [linux, windows]
        include:
          - GOOS: windows
            ext: .exe
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/cache@v2
        with:
          path: |
            pkg/web/dist
          key: autograder-web-${{ github.sha }}
      - run: CGO_ENABLED=0 GOOS=${{ matrix.GOOS }} go build -tags containers_image_openpgp -ldflags '-w -extldflags "-static"' -o autograder-server-${{ matrix.GOOS }}${{ matrix.ext }} cmd/autograder_server.go
      - run: CGO_ENABLED=0 GOOS=${{ matrix.GOOS }} go build -tags containers_image_openpgp -ldflags '-w -extldflags "-static"' -o db-seeder-${{ matrix.GOOS }}${{ matrix.ext }} cmd/db_seeder.go
      - run: zip autograder-server-${{ matrix.GOOS }}.zip autograder-server-${{ matrix.GOOS }}${{ matrix.ext }} db-seeder-${{ matrix.GOOS }}${{ matrix.ext }}
      - uses: appleboy@scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_PRIVATE_KEY }}
          passphrase: ${{ secrets.ALIYUN_PRIVATE_KEY_PASS }}
          source: autograder-server-${{ matrix.GOOS }}.zip
          target: autograder-server-${{ matrix.GOOS }}.zip
          overwrite: true

