name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linux, windows]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: arduino/setup-protoc@v1
      - run: npm install -g @angular/cli
      - run: cd web && npm install && ng build --output-path ../pkg/web/dist
      - run: GOOS=${{ matrix.GOOS }} go build -tags containers_image_openpgp -ldflags '-w -extldflags "-static"' -o autograder-server-${{ matrix.GOOS }} cmd/autograder_server.go
      - uses: actions/upload-artifact@v2
        with:
          name: autograder-server-${{ matrix.GOOS }}
          path: autograder-server-${{ matrix.GOOS }}
